model:
  model_id: "Qwen/Qwen2.5-VL-7B-Instruct"
  quantize: true

data:
  input_root: "data/raw"
  output_root: "data/captions"
  splits: ["train", "valid", "test"]
  image_extensions: [".jpg", ".jpeg", ".png"]

generation:
  prompt: "You are an Insurance adjuster. Complete a damage report for this vehicle in this image. Include details about the damage, including the location and type of damage. If there is no damage, say 'No damage'."
  use_stopping_criteria: true